# Generated by Django 5.0.3 on 2024-06-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variation',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
