# Generated by Django 5.0.3 on 2024-03-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_is_active_alter_account_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='joined_data',
            new_name='joined_date',
        ),
    ]
