# Generated by Django 5.0.3 on 2024-05-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_items_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
