# Generated by Django 5.0.3 on 2024-04-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='SavedAddress',
        ),
    ]
