# Generated by Django 3.2.12 on 2024-05-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20240527_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
