# Generated by Django 5.0.3 on 2024-05-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('SHIPPED', 'shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'cancelled'), ('RETURN', 'return')], default='PENDING', max_length=20),
        ),
    ]
