# Generated by Django 5.0.3 on 2024-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
