# Generated by Django 5.0.3 on 2024-06-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_return_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('SHIPPED', 'shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'cancelled'), ('RETURN_REQUESTED', 'return_requested'), ('RETURN_ACCEPTED', 'return_accepted'), ('RETURN_REJECTED', 'return_rejected'), ('RETURNED', 'returned')], default='PENDING', max_length=20),
        ),
    ]
